# Generated by Django 4.1 on 2024-02-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="dialog",
            fields=[
                ("dlg_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "dlg_name",
                    models.CharField(max_length=255, verbose_name="dialog name"),
                ),
                ("dlg_create", models.DateTimeField(auto_now_add=True)),
                ("dlg_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
